version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/conf.py  # Only needed if using Sphinx (ignore for MkDocs)

mkdocs:
  configuration: mkdocs.yml  # This is required for MkDocs-based documentation

