site_name: Verified Clinician Reviews
theme:
  name: readthedocs

nav:
  - Home: index.md
  - Installation: installation.md
  - Implementation: implementation.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md

